- name: ttrl-bot logs
  shell:
    cmd: cat ttrl.log
    chdir: "{{ ttrl_folder }}"
  register: log

- debug: var=log.stdout_lines

- name: ttrl-bot systemctl logs
  become: true
  shell:
    cmd: systemctl status ttrlbot.service
  register: log

- debug: var=log.stdout_lines
