---
- name: Install the TTRL Bot
  gather_facts: false
  hosts: all
  vars_prompt:
  - name: ttrl_api
    prompt: "Base URL of the backend API"
    default: https://ttrl-backend.herokuapp.com
    private: no
  - name: ttrl_log_level
    prompt: "Log level (error, warn, info, http, verbose, silly)"
    default: info
    private: no
  - name: ttrl_api_token
    prompt: "API token (leave empty to disaalow mutation operations)"
    unsafe: yes
    private: yes
  - name: ttrl_bot_token
    prompt: "BOT token (this is the auth token for the bot to authenticate against Discrod with)"
    unsafe: yes
    private: yes
  roles:
  - ttrl-install
  - ttrl-start
